import { useSelector } from 'react-redux';
import { IRootState } from '../store';

const Termsandcondition = () => {
    document.title = 'Terms & Condition | Scrapbag';
    const isRtl = useSelector((state: IRootState) => state.themeConfig.direction) === 'rtl' ? true : false;

    return (
        <div className="bg-white">
            <div className="md:-mx-[300px] font-Lato">
                <div className="bg-defaultLime w-full h-full top-0 left-0 pt-[82px] md:pt-[60px] md:rounded-custom" >
                    <div className="relative">
                        <div className="container">
                            <div className="items-center justify-center md:flex md:h-[500px] md:py-0 lg:gap-64">
                                <div className="heading mb-0 lg:text-left text-center">
                                    <div className='!text-white font-semibold text-base'>Terms & Conditions</div>
                                    <div className="text-white text-2xl lg:text-[40px] font-bold mt-5">Terms & Conditions</div>
                                </div>
                                <div className="relative mt-5 md:mt-0" data-aos='fade-left' data-aos-duration="1000">
                                    <img className="h-[17rem]" src="/assets/images/illustration_terms&conditions.png" alt="" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>


            <div className="py-14 md:py-[100px] xl:px-[300px] px-8 font-Lato">
                {/* <div className="container">
                    <div className="pb-12">
                        <h4 className="pb-5 text-xl font-bold text-black dark:text-white sm:text-2xl">Terms and Conditions</h4>
                        <p className="pb-5 text-lg font-medium">
                            This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the
                            amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This
                            electronic record is generated by a computer system and does not require any physical or digital signatures.
                        </p>
                        <p className="pb-5 text-lg font-medium">
                            his document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines)
                            Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of
                            careers.padme.com, life. padme.com & blog.padme.com website.
                        </p>
                        <p className="pb-5 text-lg font-medium">
                            This Website, including all Materials present (excluding any applicable third party materials), is the property of Myntra and is
                            copyrighted and protected by worldwide copyright laws and treaty provisions. You hereby agree to comply with all copyright laws
                            worldwide in Your use of this Website and to prevent any unauthorized copying of the Materials.
                        </p>
                        <p className="pb-5 text-lg font-medium">
                            By accessing this website we assume you accept these terms and conditions. Do not continue to use Website Name if you do not agree
                            to take all of the terms and conditions stated on this page.
                        </p>
                        <p className="text-lg font-medium">
                            The following terminology applies to these Terms and Conditions, Privacy Statement and Disclaimer Notice and all Agreements:
                            “Client”, “You” and “Your” refers to you, the person log on this website and compliant to the Company's terms and conditions. “The
                            Company”, “Ourselves”, “We”, “Our” and “Us”, refers to our Company. “Party”, “Parties”, or “Us”, refers to both the Client and
                            ourselves.
                        </p>
                    </div>
                    <div className="pb-12">
                        <h4 className="pb-5 text-xl font-bold text-black dark:text-white sm:text-2xl">Cookies</h4>
                        <p className="pb-5 text-lg font-medium">
                            We employ the use of cookies. By accessing Website Name, you agreed to use cookies in agreement with the Company Name's Privacy
                            Policy.
                        </p>
                        <p className="text-lg font-medium">
                            Most interactive websites use cookies to let us retrieve the user's details for each visit. Cookies are used by our website to
                            enable the functionality of certain areas to make it easier for people visiting our website. Some of our affiliate/advertising
                            partners may also use cookies.
                        </p>
                    </div>
                    <div className="pb-12">
                        <h4 className="pb-5 text-xl font-bold text-black dark:text-white sm:text-2xl">License</h4>
                        <p className="pb-5 text-lg font-medium">
                            Unless otherwise stated, Company Name and/or its licensors own the intellectual property rights for all material on Website Name.
                            All intellectual property rights are reserved. You may access this from Website Name for your own personal use subjected to
                            restrictions set in these terms and conditions.
                        </p>
                        <h6 className="pb-2 font-semibold text-black">You must not:</h6>
                        <ul className="pb-5 text-lg font-medium">
                            <li className="relative before:absolute before:top-3 before:h-1.5 before:w-1.5 before:rounded-full before:bg-gray ltr:pl-4 ltr:before:left-0 rtl:pr-4 rtl:before:right-0">
                                Republish material from Website Name
                            </li>
                            <li className="relative before:absolute before:top-3 before:h-1.5 before:w-1.5 before:rounded-full before:bg-gray ltr:pl-4 ltr:before:left-0 rtl:pr-4 rtl:before:right-0">
                                Sell, rent or sub-license material from Website Name
                            </li>
                            <li className="relative before:absolute before:top-3 before:h-1.5 before:w-1.5 before:rounded-full before:bg-gray ltr:pl-4 ltr:before:left-0 rtl:pr-4 rtl:before:right-0">
                                Reproduce, duplicate or copy material from Website Name
                            </li>
                            <li className="relative before:absolute before:top-3 before:h-1.5 before:w-1.5 before:rounded-full before:bg-gray ltr:pl-4 ltr:before:left-0 rtl:pr-4 rtl:before:right-0">
                                Redistribute content from Website Name
                            </li>
                        </ul>
                        <p className="pb-5 text-lg font-medium">This Agreement shall begin on the date hereof.</p>
                        <p className="pb-5 text-lg font-medium">
                            Parts of this website offer an opportunity for users to post and exchange opinions and information in certain areas of the website.
                            Company Name does not filter, edit, publish or review Comments prior to their presence on the website. Comments do not reflect the
                            views and opinions of Company Name,its agents and/or affiliates. Comments reflect the views and opinions of the person who post
                            their views and opinions.
                        </p>
                        <p className="pb-5 text-lg font-medium">
                            Company Name reserves the right to monitor all Comments and to remove any Comments which can be considered inappropriate, offensive
                            or causes breach of these Terms and Conditions.
                        </p>
                        <p className="pb-5 text-lg font-medium">
                            Company Name reserves the right to monitor all Comments and to remove any Comments which can be considered inappropriate, offensive
                            or causes breach of these Terms and Conditions.
                        </p>
                        <h6 className="pb-2 font-semibold text-black">You warrant and represent that:</h6>
                        <ul className="pb-5 text-lg font-medium ltr:pl-1 rtl:pr-1">
                            <li className="relative before:absolute before:top-3 before:h-1.5 before:w-1.5 before:rounded-full before:bg-gray ltr:pl-4 ltr:before:left-0 rtl:pr-4 rtl:before:right-0">
                                You are entitled to post the Comments on our website and have all necessary licenses and consents to do so;
                            </li>
                            <li className="relative before:absolute before:top-3 before:h-1.5 before:w-1.5 before:rounded-full before:bg-gray ltr:pl-4 ltr:before:left-0 rtl:pr-4 rtl:before:right-0">
                                The Comments do not invade any intellectual property right, including without limitation copyright, patent or trademark of any
                            </li>
                        </ul>
                        <h6 className="pb-2 font-semibold text-black">Third party;</h6>
                        <ul className="pb-5 text-lg font-medium ltr:pl-1 rtl:pr-1">
                            <li className="relative before:absolute before:top-3 before:h-1.5 before:w-1.5 before:rounded-full before:bg-gray ltr:pl-4 ltr:before:left-0 rtl:pr-4 rtl:before:right-0">
                                The Comments do not contain any defamatory, libelous, offensive, indecent or otherwise unlawful material which is an invasion of
                                privacy
                            </li>
                        </ul>
                        <p className="text-lg font-medium">
                            You hereby grant Company Name a non-exclusive license to use, reproduce, edit and authorize others to use, reproduce and edit any of
                            your Comments in any and all forms, formats or media.
                        </p>
                    </div>
                    <div>
                        <h4 className="pb-5 text-xl font-bold text-black dark:text-white sm:text-2xl">Hyperlinking to our Content</h4>
                        <p className="pb-5 text-lg font-medium">The following organizations may link to our Website without prior written approval:</p>
                        <ul className="pb-5 text-lg font-medium">
                            <li className="relative before:absolute before:top-3 before:h-1.5 before:w-1.5 before:rounded-full before:bg-gray ltr:pl-4 ltr:before:left-0 rtl:pr-4 rtl:before:right-0">
                                Government agencies;
                            </li>
                            <li className="relative before:absolute before:top-3 before:h-1.5 before:w-1.5 before:rounded-full before:bg-gray ltr:pl-4 ltr:before:left-0 rtl:pr-4 rtl:before:right-0">
                                Search engines;
                            </li>
                            <li className="relative before:absolute before:top-3 before:h-1.5 before:w-1.5 before:rounded-full before:bg-gray ltr:pl-4 ltr:before:left-0 rtl:pr-4 rtl:before:right-0">
                                News organizations;
                            </li>
                            <li className="relative before:absolute before:top-3 before:h-1.5 before:w-1.5 before:rounded-full before:bg-gray ltr:pl-4 ltr:before:left-0 rtl:pr-4 rtl:before:right-0">
                                Online directory distributors may link to our Website in the same manner as they hyperlink to the Websites of other listed
                                businesses; and System wide Accredited Businesses except soliciting non-profit organizations, charity shopping malls, and
                                charity fundraising groups
                            </li>
                        </ul>
                        <p className="text-lg font-medium">which may not hyperlink to our Web site.</p>
                    </div>
                </div> */}
                <div className='container'>
                    <div className="pb-12">
                        <h4 className="pb-5 text-xl font-bold text-black dark:text-white sm:text-2xl">Terms and Conditions</h4>
                    </div>
                    <div className="pb-12">
                        <div className='text-lg font-bold'>AGREEMENT TO OUR LEGAL TERMS</div>
                        <p>We are Emerging Climate Innovations Private Limited , doing business as Scrapbag ( 'Company', 'we', 'us', or 'our' ) , a company registered in India at 89-A, Premnagar-I, Gurjar ki thadi , Jaipur , Rajasthan 302019 .

                            We operate the website https://www.scrapbag.in (the 'Site' ), the mobile application Scrapbag (the 'App'), as well as any other related products and services that refer or link to these legal terms (the 'Legal Terms') (collectively, the 'Services').

                            Scrapbag is providing an online platform for scrap selling from households to businesses at a single click. We mainly work in Door to Door waste collection and its one stop segregation. We are on a mission to provide sustainable living and zero waste lifestyle to people.

                            You can contact us by phone at (+91)6350419507, email at support@scrapbag.in , or by mail to 89-A, Premnagar-I, Gurjar ki thadi , Jaipur , Rajasthan 302019 , India .

                            These Legal Terms constitute a legally binding agreement made between you, whether personally or on behalf of an entity ('you' ), and Emerging Climate Innovations Private Limited, concerning your access to and use of the Services. You agree that by accessing the Services, you have read, understood, and agreed to be bound by all of these Legal Terms. IF YOU DO NOT AGREE WITH ALL OF THESE LEGAL TERMS, THEN YOU ARE EXPRESSLY PROHIBITED FROM USING THE SERVICES AND YOU MUST DISCONTINUE USE IMMEDIATELY.

                            Supplemental terms and conditions or documents that may be posted on the Services from time to time are hereby expressly incorporated herein by reference. We reserve the right, in our sole discretion, to make changes or modifications to these Legal Terms at any time and for any reason. We will alert you about any changes by updating the 'Last updated' date of these Legal Terms, and you waive any right to receive specific notice of each such change. It is your responsibility to periodically review these Legal Terms to stay informed of updates. You will be subject to, and will be deemed to have been made aware of and to have accepted, the changes in any revised Legal Terms by your continued use of the Services after the date such revised Legal Terms are posted.

                            The Services are intended for users who are at least 18 years old. Persons under the age of 18 are not permitted to use or register for the Services.

                            We recommend that you print a copy of these Legal Terms for your records.
                        </p>
                    </div>

                    <div className="pb-12">
                        <div className='text-lg font-bold'>TABLE OF CONTENTS</div>
                        <ul>
                            <a href="#services">
                                <li>1. OUR SERVICES</li>
                            </a>
                            <a href="#services">
                                <li>2. INTELLECTUAL PROPERTY RIGHTS</li>
                            </a>
                            <a href="#services">
                                <li>3. USER REPRESENTATIONS</li>
                            </a>
                            <a href="#services">
                                <li>4. USER REGISTRATION</li>
                            </a>
                            <a href="#services">
                                <li>5. PROHIBITED ACTIVITIES</li>
                            </a>
                            <a href="#services">
                                <li>6. USER GENERATED CONTRIBUTIONS</li>
                            </a>

                            <a href="#services">
                                <li>7. CONTRIBUTION LICENCE</li>
                            </a>
                            <a href="#services">
                                <li>8. MOBILE APPLICATION LICENCE</li>
                            </a>
                            <a href="#services">
                                <li>9. ADVERTISERS</li>
                            </a>
                            <a href="#services">
                                <li>10. SERVICES MANAGEMENT</li>
                            </a>

                            <a href="#services">
                                <li>11. PRIVACY POLICY</li>
                            </a>
                            <a href="#services">
                                <li>12. TERM AND TERMINATION</li>
                            </a>
                            <a href="#services">
                                <li>13. MODIFICATIONS AND INTERRUPTIONS</li>
                            </a>
                            <a href="#services">
                                <li>14. GOVERNING LAW</li>
                            </a>


                            <a href="#services">
                                <li>15. DISPUTE RESOLUTION</li>
                            </a>
                            <a href="#services">
                                <li>16. CORRECTIONS</li>
                            </a>
                            <a href="#services">
                                <li>17. DISCLAIMER</li>
                            </a>
                            <a href="#services">
                                <li>18. LIMITATIONS OF LIABILITY</li>
                            </a>
                            <a href="#services">
                                <li>19. INDEMNIFICATION</li>
                            </a>

                            <a href="#services">
                                <li>20. USER DATA</li>
                            </a>
                            <a href="#services">
                                <li>21. ELECTRONIC COMMUNICATIONS, TRANSACTIONS, AND SIGNATURES</li>
                            </a>
                            <a href="#services">
                                <li>22. MISCELLANEOUS</li>
                            </a>
                            <a href="#services">
                                <li>23. CONTACT US</li>
                            </a>
                        </ul>
                    </div>

                    <div className="pb-12">
                        <div className='text-lg font-bold'>1. OUR SERVICES
                        </div>
                        <p>The information provided when using the Services is not intended for distribution to or use by any person or entity in any jurisdiction or country where such distribution or use would be contrary to law or regulation or which would subject us to any registration requirement within such jurisdiction or country. Accordingly, those persons who choose to access the Services from other locations do so on their own initiative and are solely responsible for compliance with local laws, if and to the extent local laws are applicable.</p>
                    </div>

                    <div className="pb-12">
                        <div className='text-lg font-bold'>2. INTELLECTUAL PROPERTY RIGHTS
                        </div>
                        <p className="pb-3">Our intellectual property <br />

                            We are the owner or the licensee of all intellectual property rights in our Services, including all source code, databases, functionality, software, website designs, audio, video, text, photographs, and graphics in the Services (collectively, the 'Content'), as well as the trademarks, service marks, and logos contained therein (the 'Marks').

                            Our Content and Marks are protected by copyright and trademark laws (and various other intellectual property rights and unfair competition laws) and treaties in the United States and around the world.

                            The Content and Marks are provided in or through the Services 'AS IS' for your personal, non-commercial use or internal business purpose only.
                        </p>

                        <p className="pb-3">Your use of our Services <br />

                            Subject to your compliance with these Legal Terms, including the 'PROHIBITED ACTIVITIES ' section below, we grant you a non-exclusive, non-transferable, revocable licence to:
                            access the Services; and
                            download or print a copy of any portion of the Content to which you have properly gained access.
                            solely for your personal, non-commercial use or internal business purpose.

                            Except as set out in this section or elsewhere in our Legal Terms, no part of the Services and no Content or Marks may be copied, reproduced, aggregated, republished, uploaded, posted, publicly displayed, encoded, translated, transmitted, distributed, sold, licensed, or otherwise exploited for any commercial purpose whatsoever, without our express prior written permission.

                            If you wish to make any use of the Services, Content, or Marks other than as set out in this section or elsewhere in our Legal Terms, please address your request to: support@scrapbag.in. If we ever grant you the permission to post, reproduce, or publicly display any part of our Services or Content, you must identify us as the owners or licensors of the Services, Content, or Marks and ensure that any copyright or proprietary notice appears or is visible on posting, reproducing, or displaying our Content.

                            We reserve all rights not expressly granted to you in and to the Services, Content, and Marks.

                            Any breach of these Intellectual Property Rights will constitute a material breach of our Legal Terms and your right to use our Services will terminate immediately.
                        </p>


                        <p className="pb-3">Your submissions <br />

                            Please review this section and the 'PROHIBITED ACTIVITIES ' section carefully prior to using our Services to understand the (a) rights you give us and (b) obligations you have when you post or upload any content through the Services.

                            Submissions: By directly sending us any question, comment, suggestion, idea, feedback, or other information about the Services ( 'Submissions'), you agree to assign to us all intellectual property rights in such Submission. You agree that we shall own this Submission and be entitled to its unrestricted use and dissemination for any lawful purpose, commercial or otherwise, without acknowledgment or compensation to you.

                            You are responsible for what you post or upload: By sending us Submissions through any part of the Services you:
                            confirm that you have read and agree with our 'PROHIBITED ACTIVITIES ' and will not post, send, publish, upload, or transmit through the Services any Submission that is illegal, harassing, hateful, harmful, defamatory, obscene, bullying, abusive, discriminatory, threatening to any person or group, sexually explicit, false, inaccurate, deceitful, or misleading;
                            to the extent permissible by applicable law, waive any and all moral rights to any such Submission;
                            warrant that any such Submission are original to you or that you have the necessary rights and licences to submit such Submissions and that you have full authority to grant us the above-mentioned rights in relation to your Submissions; and
                            warrant and represent that your Submissions do not constitute confidential information.
                            You are solely responsible for your Submissions and you expressly agree to reimburse us for any and all losses that we may suffer because of your breach of (a) this section, (b) any third party’s intellectual property rights, or (c) applicable law.
                        </p>
                    </div>


                    <div className="pb-12">
                        <div className='text-lg font-bold'>3. USER REPRESENTATIONS
                        </div>
                        <p>
                            By using the Services, you represent and warrant that: (1) all registration information you submit will be true, accurate, current, and complete; (2) you will maintain the accuracy of such information and promptly update such registration information as necessary; (3) you have the legal capacity and you agree to comply with these Legal Terms; (4) you are not a minor in the jurisdiction in which you reside ; (5) you will not access the Services through automated or non-human means, whether through a bot, script or otherwise; (6) you will not use the Services for any illegal or unauthorised purpose; and (7) your use of the Services will not violate any applicable law or regulation.

                            If you provide any information that is untrue, inaccurate, not current, or incomplete, we have the right to suspend or terminate your account and refuse any and all current or future use of the Services (or any portion thereof).</p>
                    </div>


                    <div className="pb-12">
                        <div className='text-lg font-bold'>4. USER REGISTRATION
                        </div>
                        <p>
                            You may be required to register to use the Services. You agree to keep your password confidential and will be responsible for all use of your account and password. We reserve the right to remove, reclaim, or change a username you select if we determine, in our sole discretion, that such username is inappropriate, obscene, or otherwise objectionable.</p>
                    </div>


                    <div className="pb-12">
                        <div className='text-lg font-bold'>5. PROHIBITED ACTIVITIES
                        </div>
                        <p>You may not access or use the Services for any purpose other than that for which we make the Services available. The Services may not be used in connection with any commercial endeavours except those that are specifically endorsed or approved by us.

                            As a user of the Services, you agree not to:
                            Systematically retrieve data or other content from the Services to create or compile, directly or indirectly, a collection, compilation, database, or directory without written permission from us.
                            Trick, defraud, or mislead us and other users, especially in any attempt to learn sensitive account information such as user passwords.
                            Circumvent, disable, or otherwise interfere with security-related features of the Services, including features that prevent or restrict the use or copying of any Content or enforce limitations on the use of the Services and/or the Content contained therein.
                            Disparage, tarnish, or otherwise harm, in our opinion, us and/or the Services.
                            Use any information obtained from the Services in order to harass, abuse, or harm another person.
                            Make improper use of our support services or submit false reports of abuse or misconduct.
                            Use the Services in a manner inconsistent with any applicable laws or regulations.
                            Engage in unauthorised framing of or linking to the Services.
                            Upload or transmit (or attempt to upload or to transmit) viruses, Trojan horses, or other material, including excessive use of capital letters and spamming (continuous posting of repetitive text), that interferes with any party’s uninterrupted use and enjoyment of the Services or modifies, impairs, disrupts, alters, or interferes with the use, features, functions, operation, or maintenance of the Services.
                            Engage in any automated use of the system, such as using scripts to send comments or messages, or using any data mining, robots, or similar data gathering and extraction tools.
                            Delete the copyright or other proprietary rights notice from any Content.
                            Attempt to impersonate another user or person or use the username of another user.
                            Upload or transmit (or attempt to upload or to transmit) any material that acts as a passive or active information collection or transmission mechanism, including without limitation, clear graphics interchange formats ( 'gifs'), 1×1 pixels, web bugs, cookies, or other similar devices (sometimes referred to as 'spyware' or 'passive collection mechanisms' or 'pcms' ).
                            Interfere with, disrupt, or create an undue burden on the Services or the networks or services connected to the Services.
                            Harass, annoy, intimidate, or threaten any of our employees or agents engaged in providing any portion of the Services to you.
                            Attempt to bypass any measures of the Services designed to prevent or restrict access to the Services, or any portion of the Services.
                            Copy or adapt the Services' software, including but not limited to Flash, PHP, HTML, JavaScript, or other code.
                            Except as permitted by applicable law, decipher, decompile, disassemble, or reverse engineer any of the software comprising or in any way making up a part of the Services.
                            Except as may be the result of standard search engine or Internet browser usage, use, launch, develop, or distribute any automated system, including without limitation, any spider, robot, cheat utility, scraper, or offline reader that accesses the Services, or use or launch any unauthorised script or other software.
                            Use a buying agent or purchasing agent to make purchases on the Services.
                            Make any unauthorised use of the Services, including collecting usernames and/or email addresses of users by electronic or other means for the purpose of sending unsolicited email, or creating user accounts by automated means or under false pretences .
                            Use the Services as part of any effort to compete with us or otherwise use the Services and/or the Content for any revenue-generating endeavour or commercial enterprise.
                            Sell or otherwise transfer your profile.
                            Use the Services to advertise or offer to sell goods and services.
                            Framing or linking to your Site without authorization.
                            Copy/adapt your Site's software (includes Flash, PHP, HTML, JavaScript, or other code).
                        </p>
                    </div>

                    <div className="pb-12">
                        <div className='text-lg font-bold'>6. USER GENERATED CONTRIBUTIONS
                        </div>
                        <p>
                            The Services does not offer users to submit or post content. We may provide you with the opportunity to create, submit, post, display, transmit, perform, publish, distribute, or broadcast content and materials to us or on the Services, including but not limited to text, writings, video, audio, photographs, graphics, comments, suggestions, or personal information or other material (collectively, 'Contributions'). Contributions may be viewable by other users of the Services and through third-party websites. When you create or make available any Contributions, you thereby represent and warrant that:
                            The creation, distribution, transmission, public display, or performance, and the accessing, downloading, or copying of your Contributions do not and will not infringe the proprietary rights, including but not limited to the copyright, patent, trademark, trade secret, or moral rights of any third party.
                            You are the creator and owner of or have the necessary licences, rights, consents, releases, and permissions to use and to authorise us, the Services, and other users of the Services to use your Contributions in any manner contemplated by the Services and these Legal Terms.
                            You have the written consent, release, and/or permission of each and every identifiable individual person in your Contributions to use the name or likeness of each and every such identifiable individual person to enable inclusion and use of your Contributions in any manner contemplated by the Services and these Legal Terms.
                            Your Contributions are not false, inaccurate, or misleading.
                            Your Contributions are not unsolicited or unauthorised advertising, promotional materials, pyramid schemes, chain letters, spam, mass mailings, or other forms of solicitation.
                            Your Contributions are not obscene, lewd, lascivious, filthy, violent, harassing, libellous, slanderous, or otherwise objectionable (as determined by us).
                            Your Contributions do not ridicule, mock, disparage, intimidate, or abuse anyone.
                            Your Contributions are not used to harass or threaten (in the legal sense of those terms) any other person and to promote violence against a specific person or class of people.
                            Your Contributions do not violate any applicable law, regulation, or rule.
                            Your Contributions do not violate the privacy or publicity rights of any third party.
                            Your Contributions do not violate any applicable law concerning child pornography, or otherwise intended to protect the health or well-being of minors.
                            Your Contributions do not include any offensive comments that are connected to race, national origin, gender, sexual preference, or physical handicap.
                            Your Contributions do not otherwise violate, or link to material that violates, any provision of these Legal Terms, or any applicable law or regulation.
                            Any use of the Services in violation of the foregoing violates these Legal Terms and may result in, among other things, termination or suspension of your rights to use the Services.
                        </p>
                    </div>

                    <div className="pb-12">
                        <div className='text-lg font-bold'>7. CONTRIBUTION LICENCE
                        </div>
                        <p>You and Services agree that we may access, store, process, and use any information and personal data that you provide and your choices (including settings).

                            By submitting suggestions or other feedback regarding the Services, you agree that we can use and share such feedback for any purpose without compensation to you.

                            We do not assert any ownership over your Contributions. You retain full ownership of all of your Contributions and any intellectual property rights or other proprietary rights associated with your Contributions. We are not liable for any statements or representations in your Contributions provided by you in any area on the Services. You are solely responsible for your Contributions to the Services and you expressly agree to exonerate us from any and all responsibility and to refrain from any legal action against us regarding your Contributions.</p>
                    </div>


                    <div className="pb-12">
                        <div className='text-lg font-bold'>8. MOBILE APPLICATION LICENCE
                        </div>
                        <p>Use Licence <br />

                            If you access the Services via the App, then we grant you a revocable, non-exclusive, non-transferable, limited right to install and use the App on wireless electronic devices owned or controlled by you, and to access and use the App on such devices strictly in accordance with the terms and conditions of this mobile application licence contained in these Legal Terms. You shall not: (1) except as permitted by applicable law, decompile, reverse engineer, disassemble, attempt to derive the source code of, or decrypt the App; (2) make any modification, adaptation, improvement, enhancement, translation, or derivative work from the App; (3) violate any applicable laws, rules, or regulations in connection with your access or use of the App; (4) remove, alter, or obscure any proprietary notice (including any notice of copyright or trademark) posted by us or the licensors of the App; (5) use the App for any revenue-generating endeavour , commercial enterprise, or other purpose for which it is not designed or intended; (6) make the App available over a network or other environment permitting access or use by multiple devices or users at the same time; (7) use the App for creating a product, service, or software that is, directly or indirectly, competitive with or in any way a substitute for the App; (8) use the App to send automated queries to any website or to send any unsolicited commercial email; or (9) use any proprietary information or any of our interfaces or our other intellectual property in the design, development, manufacture, licensing, or distribution of any applications, accessories, or devices for use with the App.

                            Apple and Android Devices <br />

                            The following terms apply when you use the App obtained from either the Apple Store or Google Play (each an 'App Distributor') to access the Services: (1) the licence granted to you for our App is limited to a non-transferable licence to use the application on a device that utilises the Apple iOS or Android operating systems, as applicable, and in accordance with the usage rules set forth in the applicable App Distributor’s terms of service; (2) we are responsible for providing any maintenance and support services with respect to the App as specified in the terms and conditions of this mobile application licence contained in these Legal Terms or as otherwise required under applicable law, and you acknowledge that each App Distributor has no obligation whatsoever to furnish any maintenance and support services with respect to the App; (3) in the event of any failure of the App to conform to any applicable warranty, you may notify the applicable App Distributor, and the App Distributor, in accordance with its terms and policies, may refund the purchase price, if any, paid for the App, and to the maximum extent permitted by applicable law, the App Distributor will have no other warranty obligation whatsoever with respect to the App; (4) you represent and warrant that (i) you are not located in a country that is subject to a US government embargo, or that has been designated by the US government as a 'terrorist supporting' country and (ii) you are not listed on any US government list of prohibited or restricted parties; (5) you must comply with applicable third-party terms of agreement when using the App, e.g. if you have a VoIP application, then you must not be in violation of their wireless data service agreement when using the App; and (6) you acknowledge and agree that the App Distributors are third-party beneficiaries of the terms and conditions in this mobile application licence contained in these Legal Terms, and that each App Distributor will have the right (and will be deemed to have accepted the right) to enforce the terms and conditions in this mobile application licence contained in these Legal Terms against you as a third-party beneficiary thereof.</p>
                    </div>


                    <div className="pb-12">
                        <div className='text-lg font-bold'>9. ADVERTISERS
                        </div>
                        <p>We allow advertisers to display their advertisements and other information in certain areas of the Services, such as sidebar advertisements or banner advertisements. We simply provide the space to place such advertisements, and we have no other relationship with advertisers.
                        </p>
                    </div>


                    <div className="pb-12">
                        <div className='text-lg font-bold'>10. SERVICES MANAGEMENT
                        </div>
                        <p>We reserve the right, but not the obligation, to: (1) monitor the Services for violations of these Legal Terms; (2) take appropriate legal action against anyone who, in our sole discretion, violates the law or these Legal Terms, including without limitation, reporting such user to law enforcement authorities; (3) in our sole discretion and without limitation, refuse, restrict access to, limit the availability of, or disable (to the extent technologically feasible) any of your Contributions or any portion thereof; (4) in our sole discretion and without limitation, notice, or liability, to remove from the Services or otherwise disable all files and content that are excessive in size or are in any way burdensome to our systems; and (5) otherwise manage the Services in a manner designed to protect our rights and property and to facilitate the proper functioning of the Services.
                        </p>
                    </div>

                    <div className="pb-12">
                        <div className='text-lg font-bold'>11. PRIVACY POLICY
                        </div>
                        <p>We care about data privacy and security. By using the Services, you agree to be bound by our Privacy Policy posted on the Services, which is incorporated into these Legal Terms. Please be advised the Services are hosted in India . If you access the Services from any other region of the world with laws or other requirements governing personal data collection, use, or disclosure that differ from applicable laws in India , then through your continued use of the Services, you are transferring your data to India , and you expressly consent to have your data transferred to and processed in India .
                        </p>
                    </div>


                    <div className="pb-12">
                        <div className='text-lg font-bold'>12. TERM AND TERMINATION
                        </div>
                        <p>These Legal Terms shall remain in full force and effect while you use the Services. WITHOUT LIMITING ANY OTHER PROVISION OF THESE LEGAL TERMS, WE RESERVE THE RIGHT TO, IN OUR SOLE DISCRETION AND WITHOUT NOTICE OR LIABILITY, DENY ACCESS TO AND USE OF THE SERVICES (INCLUDING BLOCKING CERTAIN IP ADDRESSES), TO ANY PERSON FOR ANY REASON OR FOR NO REASON, INCLUDING WITHOUT LIMITATION FOR BREACH OF ANY REPRESENTATION, WARRANTY, OR COVENANT CONTAINED IN THESE LEGAL TERMS OR OF ANY APPLICABLE LAW OR REGULATION. WE MAY TERMINATE YOUR USE OR PARTICIPATION IN THE SERVICES OR DELETE YOUR ACCOUNT AND ANY CONTENT OR INFORMATION THAT YOU POSTED AT ANY TIME, WITHOUT WARNING, IN OUR SOLE DISCRETION.

                            If we terminate or suspend your account for any reason, you are prohibited from registering and creating a new account under your name, a fake or borrowed name, or the name of any third party, even if you may be acting on behalf of the third party. In addition to terminating or suspending your account, we reserve the right to take appropriate legal action, including without limitation pursuing civil, criminal, and injunctive redress.
                        </p>
                    </div>

                    <div className="pb-12">
                        <div className='text-lg font-bold'>13. MODIFICATIONS AND INTERRUPTIONS
                        </div>
                        <p>We reserve the right to change, modify, or remove the contents of the Services at any time or for any reason at our sole discretion without notice. However, we have no obligation to update any information on our Services. We will not be liable to you or any third party for any modification, price change, suspension, or discontinuance of the Services.

                            We cannot guarantee the Services will be available at all times. We may experience hardware, software, or other problems or need to perform maintenance related to the Services, resulting in interruptions, delays, or errors. We reserve the right to change, revise, update, suspend, discontinue, or otherwise modify the Services at any time or for any reason without notice to you. You agree that we have no liability whatsoever for any loss, damage, or inconvenience caused by your inability to access or use the Services during any downtime or discontinuance of the Services. Nothing in these Legal Terms will be construed to obligate us to maintain and support the Services or to supply any corrections, updates, or releases in connection therewith.
                        </p>
                    </div>


                    <div className="pb-12">
                        <div className='text-lg font-bold'>14. GOVERNING LAW
                        </div>
                        <p>These Legal Terms shall be governed by and defined following the laws of India . Emerging Climate Innovations Private Limited and yourself irrevocably consent that the courts of India shall have exclusive jurisdiction to resolve any dispute which may arise in connection with these Legal Terms.</p>
                    </div>


                    <div className="pb-12">
                        <div className='text-lg font-bold'>15. DISPUTE RESOLUTION
                        </div>
                        <p>Binding Arbitration <br />

                            Any dispute arising out of or in connection with these Legal Terms, including any question regarding its existence, validity, or termination, shall be referred to and finally resolved by the International Commercial Arbitration Court under the European Arbitration Chamber (Belgium, Brussels, Avenue Louise, 146) according to the Rules of this ICAC, which, as a result of referring to it, is considered as the part of this clause. The number of arbitrators shall be two (2). The seat, or legal place, or arbitration shall be Jaipur, India . The language of the proceedings shall be English, Hindi. The governing law of these Legal Terms shall be substantive law of India .

                            Restrictions <br />

                            The Parties agree that any arbitration shall be limited to the Dispute between the Parties individually. To the full extent permitted by law, (a) no arbitration shall be joined with any other proceeding; (b) there is no right or authority for any Dispute to be arbitrated on a class-action basis or to utilise class action procedures; and (c) there is no right or authority for any Dispute to be brought in a purported representative capacity on behalf of the general public or any other persons.

                            Exceptions to Arbitration <br />

                            The Parties agree that the following Disputes are not subject to the above provisions concerning binding arbitration: (a) any Disputes seeking to enforce or protect, or concerning the validity of, any of the intellectual property rights of a Party; (b) any Dispute related to, or arising from, allegations of theft, piracy, invasion of privacy, or unauthorised use; and (c) any claim for injunctive relief. If this provision is found to be illegal or unenforceable, then neither Party will elect to arbitrate any Dispute falling within that portion of this provision found to be illegal or unenforceable and such Dispute shall be decided by a court of competent jurisdiction within the courts listed for jurisdiction above, and the Parties agree to submit to the personal jurisdiction of that court.</p>
                    </div>


                    <div className="pb-12">
                        <div className='text-lg font-bold'>16. CORRECTIONS
                        </div>
                        <p>There may be information on the Services that contains typographical errors, inaccuracies, or omissions, including descriptions, pricing, availability, and various other information. We reserve the right to correct any errors, inaccuracies, or omissions and to change or update the information on the Services at any time, without prior notice.</p>
                    </div>


                    <div className="pb-12">
                        <div className='text-lg font-bold'>17. DISCLAIMER
                        </div>
                        <p>THE SERVICES ARE PROVIDED ON AN AS-IS AND AS-AVAILABLE BASIS. YOU AGREE THAT YOUR USE OF THE SERVICES WILL BE AT YOUR SOLE RISK. TO THE FULLEST EXTENT PERMITTED BY LAW, WE DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, IN CONNECTION WITH THE SERVICES AND YOUR USE THEREOF, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. WE MAKE NO WARRANTIES OR REPRESENTATIONS ABOUT THE ACCURACY OR COMPLETENESS OF THE SERVICES' CONTENT OR THE CONTENT OF ANY WEBSITES OR MOBILE APPLICATIONS LINKED TO THE SERVICES AND WE WILL ASSUME NO LIABILITY OR RESPONSIBILITY FOR ANY (1) ERRORS, MISTAKES, OR INACCURACIES OF CONTENT AND MATERIALS, (2) PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO AND USE OF THE SERVICES, (3) ANY UNAUTHORISED ACCESS TO OR USE OF OUR SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION AND/OR FINANCIAL INFORMATION STORED THEREIN, (4) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM THE SERVICES, (5) ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE WHICH MAY BE TRANSMITTED TO OR THROUGH THE SERVICES BY ANY THIRD PARTY, AND/OR (6) ANY ERRORS OR OMISSIONS IN ANY CONTENT AND MATERIALS OR FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF THE USE OF ANY CONTENT POSTED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE VIA THE SERVICES. WE DO NOT WARRANT, ENDORSE, GUARANTEE, OR ASSUME RESPONSIBILITY FOR ANY PRODUCT OR SERVICE ADVERTISED OR OFFERED BY A THIRD PARTY THROUGH THE SERVICES, ANY HYPERLINKED WEBSITE, OR ANY WEBSITE OR MOBILE APPLICATION FEATURED IN ANY BANNER OR OTHER ADVERTISING, AND WE WILL NOT BE A PARTY TO OR IN ANY WAY BE RESPONSIBLE FOR MONITORING ANY TRANSACTION BETWEEN YOU AND ANY THIRD-PARTY PROVIDERS OF PRODUCTS OR SERVICES. AS WITH THE PURCHASE OF A PRODUCT OR SERVICE THROUGH ANY MEDIUM OR IN ANY ENVIRONMENT, YOU SHOULD USE YOUR BEST JUDGEMENT AND EXERCISE CAUTION WHERE APPROPRIATE.</p>
                    </div>


                    <div className="pb-12">
                        <div className='text-lg font-bold'>18. LIMITATIONS OF LIABILITY
                        </div>
                        <p>IN NO EVENT WILL WE OR OUR DIRECTORS, EMPLOYEES, OR AGENTS BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY DIRECT, INDIRECT, CONSEQUENTIAL, EXEMPLARY, INCIDENTAL, SPECIAL, OR PUNITIVE DAMAGES, INCLUDING LOST PROFIT, LOST REVENUE, LOSS OF DATA, OR OTHER DAMAGES ARISING FROM YOUR USE OF THE SERVICES, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. NOTWITHSTANDING ANYTHING TO THE CONTRARY CONTAINED HEREIN, OUR LIABILITY TO YOU FOR ANY CAUSE WHATSOEVER AND REGARDLESS OF THE FORM OF THE ACTION, WILL AT ALL TIMES BE LIMITED TO THE AMOUNT PAID, IF ANY, BY YOU TO US . CERTAIN US STATE LAWS AND INTERNATIONAL LAWS DO NOT ALLOW LIMITATIONS ON IMPLIED WARRANTIES OR THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES. IF THESE LAWS APPLY TO YOU, SOME OR ALL OF THE ABOVE DISCLAIMERS OR LIMITATIONS MAY NOT APPLY TO YOU, AND YOU MAY HAVE ADDITIONAL RIGHTS.</p>
                    </div>


                    <div className="pb-12">
                        <div className='text-lg font-bold'>19. INDEMNIFICATION
                        </div>
                        <p>You agree to defend, indemnify, and hold us harmless, including our subsidiaries, affiliates, and all of our respective officers, agents, partners, and employees, from and against any loss, damage, liability, claim, or demand, including reasonable attorneys’ fees and expenses, made by any third party due to or arising out of: (1) use of the Services; (2) breach of these Legal Terms; (3) any breach of your representations and warranties set forth in these Legal Terms; (4) your violation of the rights of a third party, including but not limited to intellectual property rights; or (5) any overt harmful act toward any other user of the Services with whom you connected via the Services. Notwithstanding the foregoing, we reserve the right, at your expense, to assume the exclusive defence and control of any matter for which you are required to indemnify us, and you agree to cooperate, at your expense, with our defence of such claims. We will use reasonable efforts to notify you of any such claim, action, or proceeding which is subject to this indemnification upon becoming aware of it.</p>
                    </div>

                    <div className="pb-12">
                        <div className='text-lg font-bold'>20. USER DATA
                        </div>
                        <p>We will maintain certain data that you transmit to the Services for the purpose of managing the performance of the Services, as well as data relating to your use of the Services. Although we perform regular routine backups of data, you are solely responsible for all data that you transmit or that relates to any activity you have undertaken using the Services. You agree that we shall have no liability to you for any loss or corruption of any such data, and you hereby waive any right of action against us arising from any such loss or corruption of such data.</p>
                    </div>


                    <div className="pb-12">
                        <div className='text-lg font-bold'>21. ELECTRONIC COMMUNICATIONS, TRANSACTIONS, AND SIGNATURES
                        </div>
                        <p>Visiting the Services, sending us emails, and completing online forms constitute electronic communications. You consent to receive electronic communications, and you agree that all agreements, notices, disclosures, and other communications we provide to you electronically, via email and on the Services, satisfy any legal requirement that such communication be in writing. YOU HEREBY AGREE TO THE USE OF ELECTRONIC SIGNATURES, CONTRACTS, ORDERS, AND OTHER RECORDS, AND TO ELECTRONIC DELIVERY OF NOTICES, POLICIES, AND RECORDS OF TRANSACTIONS INITIATED OR COMPLETED BY US OR VIA THE SERVICES. You hereby waive any rights or requirements under any statutes, regulations, rules, ordinances, or other laws in any jurisdiction which require an original signature or delivery or retention of non-electronic records, or to payments or the granting of credits by any means other than electronic means.</p>
                    </div>

                    <div className="pb-12">
                        <div className='text-lg font-bold'>22. MISCELLANEOUS
                        </div>
                        <p>These Legal Terms and any policies or operating rules posted by us on the Services or in respect to the Services constitute the entire agreement and understanding between you and us. Our failure to exercise or enforce any right or provision of these Legal Terms shall not operate as a waiver of such right or provision. These Legal Terms operate to the fullest extent permissible by law. We may assign any or all of our rights and obligations to others at any time. We shall not be responsible or liable for any loss, damage, delay, or failure to act caused by any cause beyond our reasonable control. If any provision or part of a provision of these Legal Terms is determined to be unlawful, void, or unenforceable, that provision or part of the provision is deemed severable from these Legal Terms and does not affect the validity and enforceability of any remaining provisions. There is no joint venture, partnership, employment or agency relationship created between you and us as a result of these Legal Terms or use of the Services. You agree that these Legal Terms will not be construed against us by virtue of having drafted them. You hereby waive any and all defences you may have based on the electronic form of these Legal Terms and the lack of signing by the parties hereto to execute these Legal Terms.</p>
                    </div>

                    <div className="pb-12">
                        <div className='text-lg font-bold'>23. CONTACT US
                        </div>
                        <p>In order to resolve a complaint regarding the Services or to receive further information regarding use of the Services, please contact us at: <br />

                            Emerging Climate Innovations Private Limited <br />
                            89-A, Premnagar-I, Gurjar ki thadi <br />
                            Jaipur , Rajasthan 302019 <br />
                            India <br />
                            Phone: (+91)6350419507 <br />
                            support@scrapbag.in</p>
                    </div>

                </div>
            </div>
        </div>
    );
};

export default Termsandcondition;
